#pragma once

enum class Color {
	Red,
	Green,
	Blue,
	NUM_COLOR
};

enum class PROCESS_RESULT {
	PROCESS_SUCCESS,
	ERROR_OCCURRED,
	CONNECTION_ERROR,
	DB_CREATE_ERROR,
	READ_TABLE_ERROR,
	READ_SETTINGFILE_ERROR,
	RESET_TABLE_ERROR,
	OSC_WRITE_ERROR,
	UPDATE_TABLE_ERROR,
	NUM,
};

enum class DATA_SET {
	JB_ID, //JOB_ID
	PC_ID, //PC_ID
	TP_ID, //TYPE_ID
	LUNCH, //LAUNCHED
	UPDAT, //UPDATED_AT
	NUM,
};